### PR TITLE
refact fallos, aciertos

### PR DESCRIPTION
**Pull request by maximka76667**
changed Java project version to 14

### CODE REVIEW

**Review by rubensysoecho — APPROVED** [review]
stop making me feel like a bad programmer (i am) gg.

**Comment by maximka76667** [comment]
you can review my commits and learn. Thats why i do it, i dont wanna make you feel bad programmer :(

**Comment by rubensysoecho** [comment]
i will program some happiness XDD

**Comment by maximka76667** [comment]
i like your tenacity, i think i would get tired of doing this after the first hour

**Comment by maximka76667** [comment]
and i didnt change the most of code, so i like it

**Pull request merged**
